version: "3.9"

services:
    db: 
        container_name: db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tradeoffer_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
        healthcheck:
            test: '/usr/bin/mysql --user=root --password=root --execute "SELECT 1;"'
            interval: 3s
            timeout: 30s
            retries: 10
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always

    adminer:
        image: adminer
        platform: linux/x86_64
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
            
    backend:
        platform: linux/x86_64
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        environment:
            MYSQL_HOST: db
            JWT_SECRET_TOKEN: whoisbest1231
            CORS_ORIGIN_REGEX: http([s])?:\/\/localhost
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:3001 || exit 1
            interval: 3s
            timeout: 30s
            retries: 10
            
    frontend:
        container_name: frontend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            backend:
                condition: service_healthy
        ports:
            - "3002:3002"
        environment:
            SERVER_ORIGIN: http://localhost:3001
volumes:
  mysql_data:
